services:
  postgres:
    image: postgis/postgis:17-3.4-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: "KamerConnect.EnvironmentVariables/local.env"

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    env_file: "KamerConnect.EnvironmentVariables/local.env"

  ors-app:
    build:
      context: ./
    container_name: ors-app
    ports:
      - "8081:8082"
    image:
      openrouteservice/openrouteservice:v8.0.0

      volumes:
      - ./ors-docker:/home/ors
      - ./ors-docker/graphs:/ors-core/data/graphs
      - ./ors-docker/elevation_cache:/home/ors/elevation_cache
      - ./ors-docker/config:/home/ors/config
      - ./ors-docker/logs:/home/ors/logs
      - ./ors-docker/files:/home/ors/files
    environment:
      REBUILD_GRAPHS: False
      CONTAINER_LOG_LEVEL:
        INFO
      ORS_CONFIG_LOCATION:
        ./ors-docker/home/ors/config/ors-config.yml
      XMS: 1g
      XMX:
        2g
      ADDITIONAL_JAVA_OPTS:
        ""
        
volumes:
  minio_data:
  graphs:
  elevation_cache:
  config:
  logs:
  files:
