ors:
  services:
    routing:
      enabled: true
    isochrones:
      enabled: true
  engine:
    source_file: ./ors-docker/home/ors/files/netherlands-latest.osm.pbf
    profiles:
      car:
        enabled: true
        profile: driving-car
        elevation: true
        encoder_options:
          turn_costs: true
          block_fords: false
          use_acceleration: true
        preparation:
          min_network_size: 200
          methods:
            ch:
              enabled: true
              threads: 1
              weightings: fastest