ors:
  services:
    routing:
      enabled: false
    isochrones:
      enabled: true
    matrix:
      enabled: false
    geocoding:
      enabled: false
    elevation:
      enabled: false
    mapmatching:
      enabled: false
  engine:
    source_file: ./files/netherlands-latest.osm.pbf
    profiles:
      car:
        enabled: true
        profile: driving-car
        elevation: true
        encoder_options:
          turn_costs: true
          block_fords: false
          use_acceleration: true
        preparation:
          min_network_size: 200
          methods:
            ch:
              enabled: true
              threads: 1
              weightings: fastest
      bike:
        enabled: true
        profile: cycling-regular
        elevation: true
        encoder_options:
          turn_costs: false
          block_fords: true
          use_acceleration: true
        preparation:
          min_network_size: 200
          methods:
            ch:
              enabled: true
              threads: 1
              weightings: fastest